### ISSUE TITLE
dput configuration ssh port error

### ISSUE THREAD

**Issue by ggbecker** [glenux/docker-debian-repository#4]
Shouldn't the ssh port configured in dput 49160 to reflect the one mapped by docker 49160->22?
```
	ssh_config_options =
        	Port 49160
        	StrictHostKeyChecking no
```

**Comment by glenux** [comment]
Oh yes, indeed! Good point.

I corrected the documentation, thank you.

Fixed in 13a4d00e3071e49ecffae0daf6329f771a4638b9
