### ISSUE TITLE
Auto-configure reprepro-distributions from environment variables

### ISSUE THREAD

**Issue by glenux** [glenux/docker-debian-repository#5]
Use environment variables plus a template to generate the `reprepro-distributions` file.

We need : 

* EASYREPO_ORIGIN (ex: "Some Awesome Maintainer")
* EASYREPO_LABEL (ex: "Easy Debian Repository")
* EASYREPO_ARCHITECTURES (ex: "i386 amd64 powerpc source")
* EASYREPO_SUITES (ex: "unstable/sid stable/buster")
* EASYREPO_DESCRIPTION (ex: "Easy Debian Repository {{EASYREPO_SUITE}}")

That should generate something like : 

```
Origin: Some Awesome Maintainer
Label: Easy Debian Repository
Suite: unstable
Codename: sid
Version: 3.1
Architectures: i386 amd64 powerpc source
Components: main non-free contrib
Description: Easy Debian Repository Unstable

Origin: Some Awesome Maintainer
Label: Easy Debian Repository
Suite: testing
Codename: jessie
Version: 3.1
Architectures: i386 amd64 powerpc source
Components: main non-free contrib
Description: Easy Debian Repository Testing

Origin: Some Awesome Maintainer
Label: Easy Debian Repository
Suite: stable
Codename: buster
Version: 3.1
Architectures: i386 amd64 powerpc source
Components: main non-free contrib
Description: Easy Debian Repository Stable
```

**Comment by delta523** [comment]
Hi, thank you for this project. 

I implemented a configuration generator using sed. However, in the env variable EASYREPO_SUITES, the codename for each suite must be specified since they are symlinked.

I have not yet implemented warnings should there be errors in the inputs of environment variables.

EASYREPO_SUITES=unstable,sid/stable,buster/testing,bullseye

This will generate something like:

```
Origin: Some Awesome Maintainer
Label: Easy Debian Repository
Suite: unstable
Codename: sid
Version: 3.1
Architectures: i386 amd64 powerpc source
Components: main non-free contrib
Description: Easy Debian Repository Unstable

Origin: Some Awesome Maintainer
Label: Easy Debian Repository
Suite: stable
Codename: buster
Version: 3.1
Architectures: i386 amd64 powerpc source
Components: main non-free contrib
Description: Easy Debian Repository Stable

Origin: Some Awesome Maintainer
Label: Easy Debian Repository
Suite: testing
Codename: bullseye
Version: 3.1
Architectures: i386 amd64 powerpc source
Components: main non-free contrib
Description: Easy Debian Repository Testing
```

**Comment by glenux** [comment]
Wow! Thanks for the contribution!

Indeed it is missing a few tests and a couple of other things, but it's a great base for this new feature.
I'm opening a pull request. 

Thanks :)
